-- DELIMITER //

-- CREATE PROCEDURE SignUp_New_User(new_user_id varchar(100), new_user_name varchar(100), new_password varchar(100), new_password_confirm varchar(100))
-- BEGIN
-- 	DECLARE myCount INT DEFAULT 0;
-- 	SET myCount = (SELECT COUNT(*) FROM Users WHERE user_id = new_user_id);
-- 	IF (myCount = 0) THEN
-- 	INSERT INTO Users (
-- 		user_id,
-- 		user_name,
-- 		password,
-- 		password_confirm
-- 	) VALUES (
-- 		new_user_id,
-- 		new_user_name,
-- 		new_password,
-- 		new_password_confirm
-- 	);
--     ELSE
--     SIGNAL SQLSTATE '45000'
--     SET MESSAGE_TEXT = 'User already exists';
--     END IF;
-- END //

-- DELIMITER ;