-- DELIMITER //

-- CREATE PROCEDURE Create_Chat_Room(userOne VARCHAR(50), userTwo VARCHAR(50))
-- BEGIN
-- 	DECLARE isExist INT;
-- 	DECLARE rnd_str text;
-- 	SET isExist = (SELECT EXISTS(SELECT * FROM Chats WHERE (user_one = userOne and user_two = userTwo) or 
-- 		(user_one = userTwo and user_two = userOne)));
-- 	IF isExist = 0 THEN
--     	SET rnd_str := SUBSTR(CONCAT(MD5(RAND()),MD5(RAND())),1,36);
-- 		INSERT INTO Chats (
-- 			chat_id,
-- 			user_one,
--          user_two
--         )VALUES(
-- 			rnd_str,
-- 			userOne,
--          userTwo
--         );
--         SELECT * FROM Chats WHERE ((user_one = userOne and user_two = userTwo) or 
-- 		(user_one = userTwo and user_two = userOne));
-- 	ELSE 
-- 		SELECT * FROM Chats WHERE ((user_one = userOne and user_two = userTwo) or 
-- 		(user_one = userTwo and user_two = userOne));
--     END IF;
-- END //